name: Train NFL Model

on:
  workflow_dispatch: # Activa el botón para ejecutar manualmente desde el móvil

permissions:
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python en el servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Instalar librerías
      run: pip install -r requirements.txt

    - name: Ejecutar entrenamiento del modelo
      env:
        API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
      run: python predicciones.py
